# Generated by Django 2.1.5 on 2019-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
